# ----------------------- #
#      Main Configs       #
# ----------------------- #

destination:  ./docs

gems:
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-sitemap
  # unsupported by Github Pages
  # TODO: use jekyll-assets, because we will serve generated /docs folder anyway

repository: etaroza/landing-page-theme

port: 4001

exclude:
  - Gemfile
  - Gemfile.lock

name: Pipereader
slogan: Speed reading widget for websites
title: Pipereader - speed reading widget for websites
email: hilde@pipereader.com
author: Hilde Graf
description: > # "Write an awesome description for your new site here. 
  Almost invisible yet powerful speed reading widget for content driven websites, blogs, documentation.

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

collections:
  features:
    output: true


# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap
  - title: linkedin
    url: https://twitter.com/SBootstrap
